name:
  length: 50
email:
  length: 255
password:
  length: 6
gravatar:
  size: 80
gravatar_profile:
  size: 230
category:
  length: 255
product_name:
  length: 255
product_title:
  length: 15
product_description:
  length: 20
quantity:
  default: 1
image:
  size: "50x50"
